//===-- Half-precision acospif16(x) function ------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception.
//
//
//===----------------------------------------------------------------------===//

#include "src/math/acospif16.h"
#include "src/__support/FPUtil/cast.h"

namespace LIBC_NAMESPACE_DECL {
// Generated by Sollya using the following command:
// > round(pi, SG, RN);
static constexpr float PI = 0x1.921fb6p1f;

LLVM_LIBC_FUNCTION(float16, acospif16, (float16 x)) {
    return fputil::cast<float16>(acosf16(x) / PI);  
}
} // namespace LIBC_NAMESPACE_DECL
